### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by chaiyanana** [PuYuuu/toy-example-of-iLQR#2]
请教个问题，为什么即超车又变道场景不需要考虑开辟凸空间？您是直接设每个t下的obstacle 在哪里就可以计算？

**Comment by PuYuuu** [comment]
因为只是一个ilqr的应用demo，所以没有单独做边界决策这块，而且双车道其实也没必要做，把两个最外侧的边界加上就行（不过代码里也还没有这部分

**Comment by chaiyanana** [comment]
get it

**Comment by chaiyanana** [comment]
你是工作了还是学生，如果是工作了 能不能求个内推码

**Comment by PuYuuu** [comment]
可以投看看：
![mmexport98268cd61d2a838bd95ae21c44158bd5_17263814](https://github.com/user-attachments/assets/72005efb-d234-4a60-83c7-5345e3363493)

**Comment by chaiyanana** [comment]
噢 商汤已经投过了 简历挂了。。。

**Comment by chaiyanana** [comment]
能留个VX吗？我微信 YN9381
